# This is a workflow to see what will be affected with upcoming changes

name: Terraform APPLY

# Controls when the action will run. Triggers the workflow on pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "apply"
  apply:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4
    - uses: hashicorp/setup-terraform@v3
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    # Set AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.TERRAFORM_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.TERRAFORM_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: Create google lambda layer
      run: |
        cd ./infrastructure/google_lambda_layer
        
        # Create a directory for the dependencies
        mkdir -p python

        # Install the dependencies in the python directory
        pip install -r requirements.txt -t python

        # Zip the contents of the python directory
        zip -r google-layer.zip python

    # Runs a `terraform apply` command using the runners shell
    - name: Run terraform apply
      run: |
        cd ./infrastructure
        terraform version
        terraform init
        terraform apply -auto-approve